version: "3.7"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_fai_lds
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db-scripts/fai-lds-db.sql:/docker-entrypoint-initdb.d/fai-lds-db.sql
    ports:
      - '3002:5432'